spring.application.name=tinyurl
spring.datasource.url=
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.hibernate.ddl-auto=validate
#setting prepared statements to 0 disables cache thus fixing s_1 already exists issue, but reduces performance.
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Spring Boot autoconfiguration
#logging.level.org.springframework.boot.autoconfigure=DEBUG


# Root level (everything)
logging.level.root=INFO

# application.properties
management.endpoints.web.exposure.include=*

#setting timeout for dev
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.maximumPoolSize=2